### ISSUE TITLE
Arguments in hazard subclass init (conflict with from_raster)

### ISSUE THREAD

**Issue by carmensteinmann** [CLIMADA-project/climada_petals#15]
When deprecating the set methods in the relative_cropyield hazard, I encountered an error in the from_raster method when running the unit tests:
File "/Users/carmensteinmann/Documents/CLIMADA/climada_python/climada/hazard/base.py", line 282, in from_raster haz = cls(haz_type, pool) TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given

This occurs due to the fact that the hazard type is not an argument when initialising the relative_cropyield hazard (line 100 in relative_cropyield). Chahan and me then discovered, that the arguments differ among different hazards and that this could potentially become a problem also for other hazards calling the from_raster method. (I tested using __init__(self, haz_type = HAZ_TYPE, pool=None)  which solves the issue.)

What's the best way moving forward?

**Comment by tovogt** [comment]
This is easy to fix, by just calling `cls()` and setting the pool and haz_type attribute afterwards.

But in general, there might be a problem when child classes of the Hazard class make use of positional argument. As long as that's not the case, we're fine, I think.

**Comment by chahank** [comment]
There is an easy fix to the problem of the method `from_raster`. But we should probably agree whether child-classes should in general have at least the same arguments as the parents class.

**Comment by tovogt** [comment]
Most derived classes of `Hazard` come with a fixed value for `haz_type` and that makes sense. I wouldn't enforce them to have that parameter in their constructor. So, I don't think it's a good idea to generally force child classes to accept the same arguments as the parent class.

The general rule is: When you derive from a class, make sure that all derived methods (including static and class methods) still work or, if purposely not, then fail gracefully. Ideally, there should also be unit tests for derived functionality. That's what you always have to do in all programming languages anyways when working with class inheritance. Class inheritance is a non-trivial concept and you will definitely run into all kinds of problems at some point. Sometimes, while designing a new derived class, you might also want to change the parent class, and that's also something you can do to some degree (after talking to other devs in your project), even though all other child classes might also be affected in a non-trivial way.

I think, what would make sense in a CLIMADA context, is to consider having unit tests for derived functionality. All unit tests that are applied to class A should also be applied to all derived classes of A unless they explicitly state otherwise. Of course, it's not trivial to do this without repeating yourself in the test code, but there are several ways how to organize your test cases in a way that allows you to reuse test cases for derived classes. This would be a major effort though. For now, I would suggest to only fix the `Hazard.from_raster` method and keep the more general issue for later.

**Comment by emanuel-schmid** [comment]
https://github.com/CLIMADA-project/climada_python/pull/327 suggests a fix

**Comment by emanuel-schmid** [comment]
CLIMADA-project/climada_python#327 is merged into develop.
